
workspace "Example.xcworkspace"
project "Example.xcodeproj"

use_frameworks!
platform :ios, '8.0'

target :"Example" do 
    pod 'ObjectMapperTransforms' ,:path => '../'
    pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-3'
    
    target :"ExampleTests" do
      inherit! :search_paths
    end
end

